# Generated by Django 3.2.3 on 2021-07-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='phone_number',
        ),
    ]
