# Generated by Django 3.2.3 on 2021-08-06 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_newuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='date_joined',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
