# Generated by Django 3.2.3 on 2021-08-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_group_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='bg_image',
        ),
    ]
